# 🧮 Day 3 — Linear Algebra for Machine Learning

# Introduction

Linear Algebra is one of the core mathematical foundations of Machine Learning.

Every machine learning dataset can be represented as a matrix, where each row corresponds to a data sample and each column represents a feature.

Similarly, most machine learning models perform calculations using vectors and matrices. Operations such as the dot product and matrix multiplication are used internally to generate predictions efficiently.

In this notebook, we will explore the fundamental concepts of linear algebra that are essential for understanding how machine learning models process data.

# 🎯 Learning Objectives

By the end of this notebook, you will be able to:

- Represent data samples as vectors.
- Represent datasets as matrices.
- Compute the dot product manually and using NumPy.
- Understand how machine learning models generate predictions.
- Perform matrix multiplication.
- Interpret matrix shapes and identify shape mismatch errors.

In [3]:
import numpy as np

# Why Linear Algebra is the Language of Machine Learning

Machine Learning models do not process data one value at a time. Instead, they represent data as vectors and matrices, allowing thousands or even millions of calculations to be performed efficiently.

For example:

- A single customer can be represented as a vector of features.
- A dataset containing many customers becomes a matrix.
- Model parameters are stored as vectors or matrices.
- Predictions are generated using mathematical operations such as the dot product and matrix multiplication.

Because of this, Linear Algebra is often described as the language of Machine Learning.

### Real-World Example

Imagine a bank wants to predict whether customers will apply for a loan.

Each customer has several features:

- Age
- Annual Income
- Years of Employment

One customer's information can be stored as a vector:

```
[25, 50000, 3]
```

If the bank has thousands of customers, all of these vectors are stacked together into a matrix.

Machine learning algorithms then perform mathematical operations on this matrix to generate predictions for every customer efficiently.

### Connection to Machine Learning

Almost every machine learning algorithm relies on linear algebra.

For example:

- Linear Regression computes predictions using vectors.
- Logistic Regression uses the dot product for classification.
- Neural Networks perform matrix multiplication in every layer.
- Deep Learning frameworks such as TensorFlow and PyTorch are heavily optimized for matrix operations.

Understanding vectors and matrices helps explain what machine learning models are actually doing behind the scenes.

## Key Takeaways

- Linear Algebra is the mathematical language of Machine Learning.
- Data samples are represented as vectors.
- Entire datasets are represented as matrices.
- Machine learning models perform vector and matrix operations to generate predictions efficiently.

---
# Vectors

A vector is an ordered collection of numbers arranged in a specific order.

In Machine Learning, a vector usually represents **one data sample**, where each element corresponds to one feature describing that sample.

For example, a customer's information can be represented by three features:

- Age
- Annual Income
- Years of Employment

Together, these values form a three-dimensional vector.

## Visual Representation

Customer Information

| Feature | Value |
|---------|------:|
| Age | 25 |
| Annual Income | 50000 |
| Years of Employment | 3 |

↓

Vector


\begin{bmatrix}
25 & 50000 & 3
\end{bmatrix}



Each number represents one feature, and together they describe a single customer.

In [4]:
# Create a vector representing one customer
customer = np.array([25, 50000, 3])

print(customer)

[   25 50000     3]


In [5]:
print(customer.shape)

(3,)


### Understanding the Shape

The shape `(3,)` means that the vector contains **three elements**.

Unlike a matrix, a vector has only one dimension.

Each element represents one feature:

- 25 → Age
- 50000 → Annual Income
- 3 → Years of Employment

Therefore, this vector describes one customer using three features.

In [6]:
print("Age:", customer[0])
print("Income:", customer[1])
print("Years of Employment:", customer[2])

Age: 25
Income: 50000
Years of Employment: 3


## Why Are Vectors Important?

Machine learning models do not understand words such as:

- Age
- Income
- Experience

Instead, they work with numerical vectors.

Every data sample is converted into a vector before being processed by a machine learning algorithm.

In other words:

One sample → One vector

### Connection to Machine Learning

Consider a house price prediction model.

Each house can be represented as a vector:


\begin{bmatrix}
\text{Area},\ \text{Bedrooms},\ \text{Age}
\end{bmatrix}


Example:

\begin{bmatrix}
\text180,\ 3,\ 12
\end{bmatrix}


The machine learning model receives this vector as input and uses it to predict the house price.

Similarly, in customer analytics, medical diagnosis, and recommendation systems, every observation is represented as a vector before making predictions.

## Key Takeaways

- A vector is a one-dimensional array of numbers.
- In Machine Learning, a vector usually represents one data sample.
- Each element of the vector corresponds to one feature.
- NumPy represents vectors using one-dimensional arrays.
- Understanding vectors is essential because they are the basic building blocks of machine learning models.

---
# Matrices

A matrix is a two-dimensional arrangement of numbers organized into rows and columns.

In Machine Learning, a matrix is commonly used to represent an entire dataset.

Each **row** represents one data sample, while each **column** represents one feature.

This structure allows machine learning algorithms to process multiple samples efficiently using matrix operations.

## Visual Representation

Suppose we have information about three customers.

| Customer | Age | Annual Income | Years of Employment |
|----------|----:|--------------:|--------------------:|
| Customer 1 | 25 | 50000 | 3 |
| Customer 2 | 40 | 80000 | 10 |
| Customer 3 | 33 | 62000 | 5 |

This dataset can be represented as the following matrix:

\
\begin{bmatrix}
25 & 50000 & 3 \\
40 & 80000 & 10 \\
33 & 62000 & 5
\end{bmatrix}


Rows represent customers (samples), while columns represent features.

In [7]:
# Create a dataset containing three customers

X = np.array([
    [25, 50000, 3],
    [40, 80000, 10],
    [33, 62000, 5]
])

print(X)

[[   25 50000     3]
 [   40 80000    10]
 [   33 62000     5]]


In [8]:
print(X.shape)

(3, 3)


## Understanding Matrix Shape

The shape `(3, 3)` means:

- 3 rows (samples)
- 3 columns (features)

In general,

$$
(\text{rows},\ \text{columns})
=
(\text{samples},\ \text{features})
$$

This is one of the most common notations used in Machine Learning.

In [9]:
print(X[0])

[   25 50000     3]


In [10]:
print(X[1])

[   40 80000    10]


In [11]:
print(X[:,0])

[25 40 33]


In [12]:
print(X[:,1])

[50000 80000 62000]


In [13]:
print(X[:,2])

[ 3 10  5]


### Explanation

NumPy uses indexing to access rows and columns.

- `X[0]` returns the first row (the first customer).
- `X[1]` returns the second row.
- `X[:,0]` returns all values in the first column.
- `X[:,1]` returns the Income feature.
- `X[:,2]` returns the Years of Employment feature.

The colon (`:`) means "select all rows."

## Why Are Matrices Important?

Real-world datasets usually contain thousands or even millions of samples.

Instead of processing one sample at a time, machine learning algorithms operate on the entire dataset as a matrix.

This makes computations much faster and enables efficient training and prediction.

### Connection to Machine Learning

Every machine learning dataset is stored as a matrix.

For example, a dataset containing customer information might look like this:

- Rows → Customers
- Columns → Features

During training, algorithms use this matrix together with model parameters to learn patterns from the data.

Later, the same matrix is used to generate predictions for all samples.

## Key Takeaways

- A matrix is a two-dimensional array.
- Rows represent data samples.
- Columns represent features.
- A dataset in Machine Learning is typically represented as a matrix.
- Matrix operations allow models to process multiple samples efficiently.

---
# The Dot Product

The dot product is one of the most fundamental operations in linear algebra and machine learning.

It combines two vectors by multiplying their corresponding elements and then summing the results.

The final output is a single numerical value.

In machine learning, the dot product is used to combine feature values with model weights in order to generate predictions.

## Dot Product Formula

The dot product is calculated by multiplying each feature by its corresponding weight and then summing all the products.

$$
Prediction =
(25\times0.1)
+
(50000\times0.0002)
+
(3\times1.5)
$$

In [14]:
features = np.array([25, 50000, 3])

weights = np.array([0.1, 0.0002, 1.5])

manual_prediction = (
    features[0] * weights[0] +
    features[1] * weights[1] +
    features[2] * weights[2]
)

print(manual_prediction)

17.0


In [15]:
prediction = np.dot(features, weights)

print(prediction)

17.0


### Interpretation

Both the manual calculation and NumPy produced the same prediction.

The dot product combines feature values with their corresponding weights to produce a single output.

This output represents the prediction of a linear model before adding the bias term.

## Why Is the Dot Product Important?

The dot product is at the core of many machine learning algorithms.

For example:

- Linear Regression
- Logistic Regression
- Neural Networks

All of these models compute predictions by multiplying input features by learned weights.

## Prediction Formula

A linear model computes predictions using the following equation:

$$
Prediction = \mathbf{x}\cdot\mathbf{w} + b
$$

Where:
- $\mathbf{x}$ is the feature vector.
- $\mathbf{w}$ is the weight vector.
- $b$ is the bias term.

## Connection to Machine Learning

Every time a linear regression model predicts a value, it computes the dot product between the input features and the learned weights, then adds a bias term.

This same concept is also used in logistic regression and neural networks.

Understanding the dot product helps explain how machine learning models transform input features into predictions.

## Key Takeaways

- The dot product combines two vectors into a single value.
- Each feature is multiplied by its corresponding weight.
- The products are summed to produce the prediction.
- NumPy provides the `np.dot()` function to compute the dot product efficiently.
- The dot product is one of the most important mathematical operations in machine learning.

---
# Matrix Multiplication

Matrix multiplication is one of the most important operations in Machine Learning.

Instead of computing predictions for one sample at a time, matrix multiplication allows us to generate predictions for an entire dataset in a single operation.

This makes machine learning models much faster and more efficient when working with large datasets.

In [19]:
features = np.array([25, 50000, 3])

weights = np.array([0.1, 0.0002, 1.5])

prediction = np.dot(features, weights)
print(prediction)

17.0


In [20]:
X = np.array([
    [25,50000,3],
    [40,80000,10],
    [33,62000,5]
])

weights = np.array([
    0.1,
    0.0002,
    1.5
])

In [21]:
print(X.shape)
print(weights.shape)

(3, 3)
(3,)


The dataset contains:

- 3 samples
- 3 features

The weight vector contains one weight for each feature.

Since the number of features equals the number of weights, the multiplication can be performed successfully.

In [22]:
predictions = X @ weights

print(predictions)

[17.  35.  23.2]


### Interpretation

The matrix multiplication produced one prediction for each customer.

Instead of processing each sample individually, NumPy applied the dot product to every row in the dataset automatically.

This is exactly how machine learning models generate predictions for many samples efficiently.

## Shape Matching Rule

For matrix multiplication to work, the inner dimensions must match.

$$
(m \times n)
\times
(n \times p)
=
(m \times p)
$$

The number of columns in the first matrix must equal the number of rows in the second matrix.

### Valid Multiplication

$$
(3\times3)
\times
(3\times1)
=
(3\times1)
$$

✓ Multiplication is valid.

### Invalid Multiplication

$$
(3\times3)
\times
(2\times1)
$$

✗ Multiplication is not possible because

$$
3 \neq 2
$$

In [25]:
wrong_weights = np.array([0.1,0.2])

X @ wrong_weights

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

### Why Did the Error Occur?

The dataset contains three features for every sample.

However, the weight vector contains only two values.

Because each feature must have a corresponding weight, the multiplication cannot be performed.

To fix the problem, the weight vector must contain exactly three values.

## Connection to Machine Learning

During prediction, a machine learning model multiplies the feature matrix by the learned weight vector.

This operation produces predictions for all samples simultaneously, making matrix multiplication one of the most frequently used operations in machine learning libraries such as NumPy, TensorFlow, and PyTorch.

## Key Takeaways

- Matrix multiplication computes predictions for multiple samples at once.
- The inner dimensions of the matrices must match.
- Shape mismatches are one of the most common programming errors in machine learning.
- Understanding matrix shapes helps prevent errors and makes it easier to work with machine learning models.

# Hands-On Lab

## Objective

In this lab, we will build a simple machine learning workflow using NumPy.

We will:

1. Represent a small dataset as a matrix.
2. Represent model parameters as a weight vector.
3. Compute predictions manually.
4. Verify the calculations using NumPy.
5. Generate predictions for the entire dataset using matrix multiplication.
6. Create a shape mismatch error and explain how to fix it.

This exercise demonstrates the mathematical operations performed internally by many machine learning models.

In [26]:
import numpy as np

X = np.array([
    [25, 50000, 3],
    [40, 80000, 10],
    [33, 62000, 5]
])

print(X)

[[   25 50000     3]
 [   40 80000    10]
 [   33 62000     5]]


In [27]:
print("Dataset Shape:", X.shape)

Dataset Shape: (3, 3)


### Interpretation

The dataset contains:

- **3 samples** (rows)
- **3 features** (columns)

Each row represents one customer, while each column represents one feature.

## Step 2 — Create the Weight Vector

Assume that a machine learning model has learned the following weights:

- Age → 0.1
- Income → 0.0002
- Years of Employment → 1.5

These values represent the importance of each feature when generating predictions.

In [28]:
weights = np.array([0.1, 0.0002, 1.5])

print(weights)

[1.0e-01 2.0e-04 1.5e+00]


In [29]:
print("Weight Shape:", weights.shape)

Weight Shape: (3,)


### Interpretation

The weight vector contains one weight for each feature.

Since our dataset has three features, the weight vector also contains three values.

## Step 3 — Manual Prediction

Before using NumPy, we will manually calculate the prediction for the first customer.

Customer Features:

- Age = 25
- Income = 50000
- Years = 3

In [30]:
manual_prediction = (
    25 * 0.1 +
    50000 * 0.0002 +
    3 * 1.5
)

print(manual_prediction)

17.0


### Manual Calculation

$$
Prediction =
(25 \times 0.1)
+
(50000 \times 0.0002)
+
(3 \times 1.5)
$$

$$
=
2.5 + 10 + 4.5
=
17
$$

## Step 4 — Verify the Result with NumPy

Instead of calculating each multiplication manually, NumPy provides the `np.dot()` function.

In [32]:
prediction = np.dot(X[0], weights)

print(prediction)

17.0


### Interpretation

The prediction produced by `np.dot()` is identical to the manual calculation.

This confirms that the dot product multiplies each feature by its corresponding weight and sums the results correctly.

## Step 5 — Matrix Multiplication

Rather than predicting one customer at a time, we can generate predictions for the entire dataset using matrix multiplication.

In [33]:
predictions = X @ weights

print(predictions)

[17.  35.  23.2]


In [34]:
for i, prediction in enumerate(predictions, start=1):
    print(f"Customer {i}: {prediction:.2f}")

Customer 1: 17.00
Customer 2: 35.00
Customer 3: 23.20


### Interpretation

Matrix multiplication generated one prediction for every customer simultaneously.

Instead of calling `np.dot()` for each individual sample, NumPy automatically applied the dot product to every row in the dataset.

This approach is significantly more efficient and is commonly used in machine learning libraries.

## Step 6 — Shape Mismatch

A common programming mistake in machine learning is attempting to multiply matrices with incompatible shapes.

Let's intentionally create this error.

In [35]:
wrong_weights = np.array([0.1, 0.2])

X @ wrong_weights

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

### Why Did This Error Occur?

The dataset contains **three features** for each sample.

However, the weight vector contains only **two values**.

Since every feature must have a corresponding weight, matrix multiplication cannot be performed.

To fix this problem, the weight vector must contain exactly three values.

In [36]:
correct_weights = np.array([
    0.1,
    0.0002,
    1.5
])

predictions = X @ correct_weights

print(predictions)

[17.  35.  23.2]


### Interpretation

After providing one weight for each feature, the matrix multiplication succeeds.

Matching matrix dimensions is essential when working with machine learning models.

# Lab Findings

- A single customer can be represented as a feature vector.
- Multiple customers can be stored in a matrix.
- The dot product combines feature values with model weights to generate one prediction.
- Matrix multiplication efficiently computes predictions for all samples at once.
- Matrix dimensions must be compatible before multiplication can be performed.
- Understanding vectors, matrices, and matrix multiplication is essential for building and debugging machine learning models.

# Reflection

Today, I developed a stronger understanding of how linear algebra forms the mathematical foundation of machine learning.

Working with vectors and matrices helped me understand how data is represented inside machine learning models. The dot product demonstrated how feature values are combined with learned weights to generate predictions, while matrix multiplication showed how predictions can be efficiently computed for multiple samples at once.

The hands-on exercises also highlighted the importance of matrix dimensions and reinforced the need to understand array shapes when working with NumPy. Overall, this notebook strengthened both my mathematical intuition and my practical programming skills.

# Conclusion

In this notebook, I explored the essential concepts of linear algebra used in machine learning.

I learned how to represent individual samples as vectors, organize datasets into matrices, compute predictions using the dot product, and perform matrix multiplication efficiently with NumPy. I also investigated shape mismatch errors and learned how to identify and resolve them.

These concepts provide the mathematical foundation for many machine learning algorithms and will be essential when studying models such as Linear Regression, Logistic Regression, and Neural Networks in the upcoming weeks.