# Day 3: NumPy - Numerical Computing

## Learning Objectives

By the end of this notebook, I will be able to:

- Understand why NumPy is essential for Data Science and AI.
- Create NumPy arrays using different methods.
- Inspect array properties such as shape, dtype, ndim, and size.
- Index and slice one-dimensional and two-dimensional arrays.
- Apply vectorized operations without explicit loops.
- Filter data using Boolean Masking.
- Understand and use Broadcasting.

# Introduction to NumPy

NumPy (Numerical Python) is the fundamental numerical computing library in Python.

It introduces the ndarray (N-dimensional array), which stores data more efficiently than Python lists and performs mathematical operations significantly faster.

Many popular libraries—including Pandas, Scikit-learn, TensorFlow, and PyTorch—are built on top of NumPy.

## Why NumPy?

Python lists are flexible but become inefficient when working with large numerical datasets.

NumPy solves this by providing:

- Faster numerical computations
- Lower memory usage
- Built-in mathematical operations
- Efficient multidimensional arrays

These features make NumPy the foundation of modern AI and Machine Learning.

## Import NumPy

In [45]:
import numpy as np

## NumPy Arrays (ndarray)

The main object in NumPy is called ndarray.

Unlike Python lists, all elements inside a NumPy array share the same data type, allowing operations to be executed much more efficiently.

## Python List vs NumPy Array

In [47]:
python_list = [1, 2, 3, 4]

numpy_array = np.array([1, 2, 3, 4])

print("Python List:", python_list)
print("NumPy Array:", numpy_array)

Python List: [1, 2, 3, 4]
NumPy Array: [1 2 3 4]


Although they may look similar, NumPy arrays support efficient mathematical operations and consume less memory than Python lists.

## Creating arrays

NumPy provides multiple ways to create arrays depanding on the required structure and values.

Common methods include:
- np.array()
- np.zeros()
- np.ones()
- np.arange()
- np.linspace()
- np.random.rand()

In [48]:
# Creating an array from a python list
a = np.array([1, 2, 3, 4])

# Array filled with zeros
zeros = np.zeros((2, 3))

# Array filled with zeros
ones = np.ones(5)

# Sequence of values - np.arange(start, stop, step)
range_array = np.arange(0, 10, 2)

# Evenly spaced values - np.linspace(start, stop, num)
line_array = np.linspace(0, 1, 5)

# Random values
random_array = np.random.rand(3, 3)

print(a)
print(zeros)
print(ones)
print(range_array)
print(line_array)
print(random_array)

[1 2 3 4]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.91653597 0.94113082 0.47197139]
 [0.9785396  0.21710199 0.84696284]
 [0.49447073 0.40200789 0.9257947 ]]


## Reshaping Arrays

The reshape() function changes the dimensions of an array without modifying its data.

It is commonly used when preparing datasets for Machine Learning models.

In [49]:
numbers = np.arange(1,17)

matrix = numbers.reshape(4,4)

print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


## Array Attributes

Every NumPy array has important properties:

- **shape**: describes the dimensions of the array
- **dtype**: shows the data type of elements
- **ndim**: shows the number of dimensions
- **size**:  total number of elements

In [51]:
matrix = np.array([[1, 2, 3], 
                  [4, 5, 6]])

print("Shape:", matrix.shape)
print("Data type:", matrix.dtype)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)

Shape: (2, 3)
Data type: int64
Dimensions: 2
Size: 6


## Indexing and Slicing

### Indexing
Indexing allows accessing a specific element using its row and column indices.

NumPy indexing is similar to Python lists but supports multiple dimensions.

For 1D arrays, indexing works like Python lists.

For 2D arrays:  array[row, column]

Where:
- row represents the row index.
- column represents the column index.

Indexing starts from 0, meaning the first element has index 0.

In [54]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

print(matrix[0,0])

print(matrix[1,1])

print(matrix[-1,-1])

1
5
6


### Slicing

Slicing extracts a subset of an array without modifying the original data.

In [55]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

print(matrix[:,1])

print(matrix[-1,:])

print(matrix[:1,:2])

[2 5]
[4 5 6]
[[1 2]]


## Boolean Masking

Boolean masking allows selecting elements based on a condition.

It is commonly used in data filtering and cleaning.

In [21]:
numbers = np.array([1, 2, 3, 4, 5, 6])

mask = numbers > 3

print("Boolean:", mask)
print("Values:", numbers[mask])

Boolean: [False False False  True  True  True]
Values: [4 5 6]


## Vectorized Operations

Vectorization allows applying operations to entire arrays without writing explicit loops.

It makes code faster, cleaner, and more suitable for large datasets.

In [23]:
a = np.array([1, 2, 3, 4])

print(a * 2)
print(a + a)
print(a.mean())

[2 4 6 8]
[2 4 6 8]
2.5


## Broadcasting

Broadcasting allows NumPy to perform operations between arrays with compatible shapes.

It avoids unnecessary copying of data and simplifies mathematical operations.

In [25]:
martix = np.array([[1, 2, 3], 
                    [4, 5, 6]])

row = np.array([10, 20, 30])

result = matrix + row
print(result)

[[11 22 33]
 [14 25 36]]


## NumPy Array Manipulation

### Tasks:
1. Create a 4x4 array containing values from 1 to 16 and Print its shape and data type.
3. Extract the second column and last row.
4. Select values greater than the mean.
5. Apply broadcasting by adding a row array.

In [33]:
# Step 1

array = np.arange(1, 17).reshape(4, 4)

print(array)
print()
print("Shape:", array.shape)
print("Data type:", array.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Shape: (4, 4)
Data type: int64


In [39]:
# Step 2

second_column = array[:, 1]
last_row = array[-1, :]

print("Second column:", second_column)
print("Last row:", last_row)

Second column: [ 2  6 10 14]
Last row: [13 14 15 16]


In [43]:
# Step 3

mean_value = array.mean()

print(mean_value)
print("Values greater the the mean:", array[array > mean_value])

8.5
Values greater the the mean: [ 9 10 11 12 13 14 15 16]


In [44]:
# Step 4

row = np.array([10, 20, 30, 40])

result = array + row
print(result)

[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]
 [23 34 45 56]]


## Conclusion

In this notebook, I practiced the fundamental NumPy concepts required for Data Science and AI workflows.

Key topics covered:
- Creating and manipulating NumPy arrays.
- Understanding array properties.
- Indexing and slicing multidimensional arrays.
- Boolean masking for data filtering.
- Vectorized operations.
- Broadcasting.

These concepts are essential for effecient numerical computation and will be used in upcoming Machine Learning tasks.